import { defineConfig } from 'oxlint';

export default defineConfig({
    jsPlugins: ['@stylistic/eslint-plugin'],
    rules: {
        'accessor-pairs': 'error',
        'array-callback-return': 'error',
        curly: 'warn',
        'default-param-last': 'error',
        '@stylistic/dot-location': ['warn', 'property'],
        eqeqeq: 'warn',
        'guard-for-in': 'warn',
        'no-caller': 'error',
        'no-constructor-return': 'warn',
        'no-empty-pattern': 'warn',
        'no-eval': 'error',
        'no-extend-native': 'error',
        'no-extra-bind': 'warn',
        '@stylistic/no-floating-decimal': 'warn',
        'no-global-assign': 'error',
        'no-iterator': 'error',
        'no-labels': 'error',
        'no-lone-blocks': 'error',
        'no-loop-func': 'error',
        '@stylistic/no-multi-spaces': 'warn',
        'no-new-func': 'error',
        'no-new-wrappers': 'error',
        'no-nonoctal-decimal-escape': 'warn',
        'no-param-reassign': 'warn',
        'no-proto': 'error',
        'no-redeclare': 'warn',
        'no-script-url': 'error',
        'no-self-assign': 'warn',
        'no-self-compare': 'error',
        'no-throw-literal': 'error',
        'no-useless-call': 'warn',
        'no-useless-catch': 'warn',
        'no-useless-concat': 'warn',
        'no-useless-escape': 'warn',
        'no-useless-return': 'warn',
        'no-with': 'error',
        'vars-on-top': 'warn',
        '@stylistic/wrap-iife': 'warn',
        yoda: 'warn',
    },
});
