import { defineConfig } from 'oxlint';

export default defineConfig({
    jsPlugins: ['@stylistic/eslint-plugin'],
    rules: {
        'for-direction': 'error',
        'getter-return': ['error', { allowImplicit: true }],
        'no-await-in-loop': 'warn',
        'no-compare-neg-zero': 'error',
        'no-cond-assign': 'error',
        'no-console': 'warn',
        'no-debugger': 'warn',
        'no-dupe-else-if': 'error',
        'no-dupe-keys': 'error',
        'no-duplicate-case': 'error',
        'no-empty': ['warn', { allowEmptyCatch: true }],
        'no-empty-character-class': 'warn',
        'no-ex-assign': 'error',
        'no-extra-boolean-cast': 'warn',
        '@stylistic/no-extra-semi': 'error',
        'no-func-assign': 'error',
        'no-import-assign': 'error',
        'no-inner-declarations': 'error',
        'no-invalid-regexp': 'warn',
        'no-irregular-whitespace': ['warn', { skipStrings: true }],
        'no-loss-of-precision': 'error',
        'no-misleading-character-class': 'error',
        'no-obj-calls': 'error',
        'no-setter-return': 'error',
        'no-sparse-arrays': 'warn',
        'no-template-curly-in-string': 'error',
        'no-unexpected-multiline': 'warn',
        'no-unreachable': 'warn',
        'no-unsafe-negation': 'error',
        'no-unsafe-optional-chaining': 'error',
        'no-useless-backreference': 'warn',
        'use-isnan': 'error',
        'valid-typeof': 'error',
        'no-unused-private-class-members': 'warn',
        'no-constant-binary-expression': 'error',
    },
});
