import { defineConfig } from 'oxlint';
import semver from 'semver';
import { buildDynamicConfig } from '../dynamic-config/buildDynamicConfig.js';

const dynamicConfig = buildDynamicConfig();

export default defineConfig({
    plugins: ['react'],
    jsPlugins: [{ name: 'react-js', specifier: 'eslint-plugin-react' }],
    settings: {
        react: {
            version: dynamicConfig.react ?? '19.0.0',
        },
    },
    rules: {
        'react/button-has-type': 'warn',
        'react-js/default-props-match-prop-types': 'warn',
        'react-js/jsx-curly-newline': 'warn',
        'react/jsx-no-script-url': 'error',
        'react/jsx-no-useless-fragment': ['warn', { allowExpressions: true }],
        'react-js/no-access-state-in-setstate': 'warn',
        'react-js/no-adjacent-inline-elements': 'warn',
        'react/no-array-index-key': 'warn',
        'react/no-children-prop': 'error',
        'react/no-danger-with-children': 'error',
        'react-js/no-deprecated': 'warn',
        'react/no-did-mount-set-state': 'warn',
        'react-js/no-did-update-set-state': 'warn',
        'react/no-direct-mutation-state': 'warn',
        'react/no-find-dom-node': 'error',
        'react/no-is-mounted': 'error',
        'react/no-multi-comp': ['warn', { ignoreStateless: true }],
        'react/no-render-return-value': 'error',
        'react/no-string-refs': 'error',
        'react/no-this-in-sfc': 'error',
        'react-js/no-typos': 'error',
        'react/no-unescaped-entities': 'error',
        'react-js/no-unused-prop-types': 'warn',
        'react-js/no-unused-state': 'warn',
        'react/no-will-update-set-state': 'error',
        'react/prefer-es6-class': 'warn',
        'react-js/prefer-stateless-function': ['warn', { ignorePureComponents: true }],
        'react-js/prop-types': ['warn', { ignore: ['children', 'params'] }],
        'react/react-in-jsx-scope': dynamicConfig.react && semver.gte(dynamicConfig.react, '17.0.0') ? 'off' : 'error',
        'react/require-render-return': 'error',
        'react/self-closing-comp': 'warn',
        'react-js/sort-comp': [
            'warn',
            {
                order: ['static-variables', 'static-methods', 'instance-variables', 'lifecycle', 'everything-else', 'render'],
                groups: {
                    lifecycle: [
                        'displayName',
                        'propTypes',
                        'contextTypes',
                        'childContextTypes',
                        'mixins',
                        'statics',
                        'defaultProps',
                        'getDefaultProps',
                        'state',
                        'getInitialState',
                        'constructor',
                        'getChildContext',
                        'getDerivedStateFromProps',
                        'componentWillMount',
                        'UNSAFE_componentWillMount',
                        'componentDidMount',
                        'componentWillReceiveProps',
                        'UNSAFE_componentWillReceiveProps',
                        'shouldComponentUpdate',
                        'componentWillUpdate',
                        'UNSAFE_componentWillUpdate',
                        'getSnapshotBeforeUpdate',
                        'componentDidUpdate',
                        'componentDidCatch',
                        'componentWillUnmount',
                    ],
                },
            },
        ],
        'react/jsx-boolean-value': ['warn', 'always'],
        'react-js/jsx-closing-bracket-location': ['warn', 'tag-aligned'],
        'react-js/jsx-closing-tag-location': 'warn',
        'react/jsx-curly-brace-presence': [
            'warn',
            {
                props: 'never',
                children: 'never',
            },
        ],
        'react-js/jsx-curly-spacing': ['warn', 'never'],
        'react-js/jsx-equals-spacing': ['warn', 'never'],
        'react/jsx-filename-extension': ['error', { extensions: ['.js', '.jsx', '.tsx', '.mdx'] }],
        'react/jsx-fragments': ['warn', 'element'],
        'react/jsx-handler-names': 'warn',
        'react-js/jsx-indent': ['warn', 4],
        'react/jsx-key': 'error',
        'react/jsx-max-depth': ['warn', { max: 13 }],
        'react-js/jsx-max-props-per-line': ['warn', { maximum: 1, when: 'multiline' }],
        'react-js/jsx-no-bind': [
            'warn',
            {
                ignoreRefs: true,
                ignoreDOMComponents: false,
            },
        ],
        'react/jsx-no-comment-textnodes': 'error',
        'react/jsx-no-duplicate-props': 'warn',
        'react/jsx-no-undef': 'error',
        'react/jsx-pascal-case': 'warn',
        'react-js/jsx-props-no-multi-spaces': 'warn',
        'react-js/jsx-tag-spacing': [
            'warn',
            {
                closingSlash: 'never',
                beforeSelfClosing: 'never',
                afterOpening: 'never',
                beforeClosing: 'never',
            },
        ],
        'react-js/jsx-wrap-multilines': 'warn',
        'react-js/static-property-placement': 'warn',
        'react/rules-of-hooks': 'error',
        'react/exhaustive-deps': 'error',
        'react-js/no-unstable-nested-components': ['error', { allowAsProps: true }],
        'react/no-namespace': 'error',
        'react-js/no-arrow-function-lifecycle': 'warn',
        'react-js/jsx-no-leaked-render': ['error', { validStrategies: ['ternary'] }],
        'react/jsx-no-constructed-context-values': 'error',
        'react/iframe-missing-sandbox': 'error',
    },
    overrides: [
        {
            files: ['**/*.ts', '**/*.tsx'],
            rules: {
                'react-js/prop-types': 'off',
                'react-js/no-unused-prop-types': 'off',
                'react/jsx-no-undef': 'off',
                'react-js/default-props-match-prop-types': 'off',
            },
        },
        {
            files: [
                '**/*.test.ts',
                '**/*.test.tsx',
                '**/__mocks__/**/*.ts',
                '**/__mocks__/**/*.tsx',
                '**/*.spec.ts',
                '**/*.spec.tsx',
                '**/*.test-e2e.ts',
                '**/*.test-e2e.tsx',
                '**/*.spec-e2e.ts',
                '**/*.spec-e2e.tsx',
            ],
            rules: {
                'react-js/jsx-no-bind': 'off',
            },
        },
    ],
});
