import { defineConfig } from 'oxlint';

export default defineConfig({
    jsPlugins: ['@stylistic/eslint-plugin'],
    rules: {
        '@stylistic/array-bracket-spacing': 'warn',
        '@stylistic/block-spacing': 'warn',
        '@stylistic/comma-dangle': [
            'warn',
            {
                arrays: 'always-multiline',
                objects: 'always-multiline',
                imports: 'always-multiline',
                exports: 'always-multiline',
                functions: 'always-multiline',
                enums: 'always-multiline',
                generics: 'always-multiline',
                tuples: 'always-multiline',
            },
        ],
        '@stylistic/comma-spacing': 'warn',
        '@stylistic/comma-style': 'warn',
        '@stylistic/computed-property-spacing': 'warn',
        '@stylistic/eol-last': 'warn',
        '@stylistic/function-call-spacing': 'warn',
        'func-names': 'warn',
        '@stylistic/function-call-argument-newline': ['warn', 'consistent'],
        'grouped-accessor-pairs': 'warn',
        '@stylistic/indent': ['warn', 4, { SwitchCase: 1 }],
        '@stylistic/jsx-quotes': ['warn', 'prefer-double'],
        '@stylistic/key-spacing': 'warn',
        '@stylistic/keyword-spacing': 'warn',
        '@stylistic/lines-between-class-members': ['warn', 'always', { exceptAfterSingleLine: true }],
        '@stylistic/max-len': ['warn', 140, 4],
        '@stylistic/newline-per-chained-call': ['warn', { ignoreChainWithDepth: 3 }],
        'no-array-constructor': 'error',
        'no-lonely-if': 'error',
        '@stylistic/no-mixed-spaces-and-tabs': 'warn',
        '@stylistic/no-multiple-empty-lines': ['warn', { max: 1 }],
        'no-negated-condition': 'warn',
        'no-nested-ternary': 'warn',
        'no-object-constructor': 'error',
        '@stylistic/no-tabs': 'warn',
        '@stylistic/no-trailing-spaces': 'warn',
        'no-unneeded-ternary': 'warn',
        '@stylistic/no-whitespace-before-property': 'warn',
        '@stylistic/object-curly-spacing': ['warn', 'always'],
        '@stylistic/padded-blocks': ['warn', { blocks: 'never', classes: 'always', switches: 'never' }],
        '@stylistic/quote-props': ['warn', 'as-needed'],
        '@stylistic/quotes': ['warn', 'single', { avoidEscape: true }],
        '@stylistic/semi': ['warn', 'always'],
        '@stylistic/semi-spacing': 'warn',
        '@stylistic/space-before-blocks': 'warn',
        '@stylistic/space-before-function-paren': ['warn', { anonymous: 'always', named: 'never' }],
        '@stylistic/space-in-parens': 'warn',
        '@stylistic/template-tag-spacing': 'warn',
    },
});
