import { defineConfig } from 'oxlint';
import { buildDynamicConfig } from '../dynamic-config/buildDynamicConfig.js';

const dynamicConfig = buildDynamicConfig();

export default defineConfig({
    plugins: ['typescript'],
    overrides: [{
        files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
        jsPlugins: ['@stylistic/eslint-plugin'],
        rules: {
            '@stylistic/member-delimiter-style': 'warn',
            '@stylistic/type-annotation-spacing': 'warn',
            '@stylistic/indent': ['warn', 4, { SwitchCase: 1 }],
            '@stylistic/no-extra-semi': 'warn',
            '@stylistic/quotes': ['warn', 'single', { avoidEscape: true }],
            '@stylistic/semi': ['warn', 'always'],
            '@stylistic/space-before-function-paren': ['warn', { anonymous: 'always', named: 'never' }],
            'default-param-last': 'off',
            'typescript/default-param-last': 'error',
            'no-array-constructor': 'off',
            'typescript/no-array-constructor': 'error',
            'no-dupe-class-members': 'off',
            'typescript/no-dupe-class-members': 'error',
            'typescript/no-empty-function': 'warn',
            'typescript/no-explicit-any': ['warn', { ignoreRestArgs: true }],
            'typescript/no-extra-non-null-assertion': 'warn',
            'typescript/no-misused-new': 'error',
            'typescript/no-non-null-asserted-optional-chain': 'warn',
            'typescript/no-require-imports': 'warn',
            'typescript/no-this-alias': 'warn',
            'typescript/no-unused-expressions': ['warn', { allowTernary: true }],
            'no-unused-vars': 'off',
            'typescript/no-unused-vars': ['warn', { ignoreRestSiblings: true }],
            'typescript/no-use-before-define': [
                'warn',
                {
                    functions: false,
                    classes: false,
                    enums: true,
                    variables: true,
                    typedefs: false,
                },
            ],
            'no-useless-constructor': 'off',
            'typescript/no-useless-constructor': 'warn',
            'typescript/strict-boolean-expressions': dynamicConfig.typescript?.config?.strictNullChecks ? 'warn' : 'off',
            'no-redeclare': 'off',
            'typescript/no-redeclare': 'error',
            'no-shadow': 'off',
            'typescript/no-shadow': ['warn', { ignoreOnInitialization: true }],
            'typescript/array-type': ['warn', { default: 'array-simple' }],
            'typescript/adjacent-overload-signatures': 'warn',
            'typescript/ban-ts-comment': 'warn',
            'typescript/consistent-type-assertions': ['warn', { assertionStyle: 'as' }],
            'typescript/no-for-in-array': 'error',
            'typescript/no-implied-eval': 'error',
            'typescript/no-inferrable-types': [
                'warn',
                {
                    ignoreParameters: true,
                    ignoreProperties: true,
                },
            ],
            'typescript/no-misused-promises': ['error', { checksVoidReturn: false }],
            'no-throw-literal': 'off',
            'typescript/only-throw-error': 'warn',
            'typescript/no-unnecessary-qualifier': 'warn',
            'typescript/no-unnecessary-type-arguments': 'warn',
            'typescript/prefer-as-const': 'warn',
            'typescript/prefer-for-of': 'warn',
            'typescript/prefer-includes': 'warn',
            'typescript/prefer-namespace-keyword': 'error',
            'typescript/prefer-optional-chain': 'warn',
            'typescript/prefer-string-starts-ends-with': 'warn',
            'typescript/require-await': 'error',
            'typescript/triple-slash-reference': 'error',
            'typescript/no-duplicate-type-constituents': 'warn',
            'typescript/consistent-type-imports': [
                'warn',
                {
                    prefer: 'type-imports',
                    fixStyle: 'inline-type-imports',
                    disallowTypeAnnotations: false,
                },
            ],
        },
    }],
});
